### ISSUE TITLE
How to determine "All day" event

### ISSUE THREAD

**Issue by dixonsiu** [personium/app-personium-calendar#41]
Office365では例えば、VEventのstart Dateが2017-12-25 00:00:00  end Dateが2017-12-26 00:00:00となっているのがall dayとなっています。

**Comment by dixonsiu** [comment]
Yamashima-san's note.  

ちなみにREST APIで取得するイベント情報の中でall-dayはどのように表現されているかと言うと、Googleではイベント開始時刻の「start」かイベント終了時刻の「end」の内容が「date」タイプか「dateTime」タイプで区別しているようです。
 "start": {
   "date": date,　　　　　　　←どちらかが設定されている
   "dateTime": datetime,　　　←どちらかが設定されている
   "timeZone": string
 },

Office365では、「IsAllDay」キーがあり「true」ならall-day, 「false」ならall-dayではないのですが、イベント開始時刻の「Start」とイベント終了時刻の「End」が24時間以上間隔が開いていなければ登録失敗となります。ですのでOffice365の場合は「Start」「End」は常にdateTimeで登録されています。

**Comment by dixonsiu** [comment]
First, must save the original datetime string to the OData and use it to determine All-day event or not.  

For Google, I think all-day event has date key and only include date (no time) in that value.

**Comment by HiroyukiYamashima** [comment]
そうですね。少なくともODataにAll-day event or not のフラグと言いますか、Office365のような isAllDay :  true/falseは必要ですね。
あと、設定したTimeZoneが分からないと表示の時に困ると思いますが、どうでしょうか？

**Comment by dixonsiu** [comment]
Rewrote how the data is stored.  
 - [x] [Google](https://github.com/dixonsiu/app-personium-calendar/blob/master/bar/90_contents/SyncEngine/google_cal.js#L26)  
- [x] [Office365](https://github.com/dixonsiu/app-personium-calendar/blob/master/bar/90_contents/SyncEngine/outlook_cal.js#L68)
